# Initialized `interceptors.py` generated by ipm.
# Regists your pre-interceptors and interceptors here.
# Documents at https://docs.hydroroll.team/ipm

from infini.register import Register


register = Register()
