# Initialized `events.py` generated by ipm.
# Regists your text events and regist global variables here.
# Documents at https://docs.hydroroll.team/ipm

from .events import register as events_register
from .handlers import register as handlers_register
from .interceptors import register as interceptors_register

__all__ = ["events_register", "handlers_register", "interceptors_register"]