# Initialized `events.py` generated by ipm.
# Regists your text events and regist global variables here.
# Documents at https://ipm.hydroroll.team/

from infini.register import Register


register = Register()
