# Initialized `events.py` generated by ipm.
# Regists your text events and regist global variables here.
# Documents at https://docs.hydroroll.team/ipm

from infini.register import Register


register = Register()
