# Initialized `interceptors.py` generated by ipm.
# Regists your pre-interceptors and interceptors here.
# Documents at https://ipm.hydroroll.team/

from infini.register import Register


register = Register()
