[project]
name = "examples"
version = "0.1.0"
description = "EXAMPLES 规则包"
authors = [
    {name = "admin",email = "admin@example.com"},
]
license = "MIT"
webpage = ""
unzip = 1

[requirements]

[dependencies]
