from pathlib import Path

DEBUG = False

INDEX = "https://ipm.hydroroll.team/index/"
HOME = Path.home() / ".ipm" / "src"
ATTENSION = """# This file is @generated by IPM.
# It is not intended for manual editing."""
