on:
  push:
  workflow_dispatch:

jobs:
  test-api:
    name: test commit
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - run: |
          pwd
          cd tests
          python3 -m test-api.py