on:
  push:
  workflow_dispatch:

jobs:
  test-api:
    name: test commit
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: setup pdm
        run: pip install pdm

      - run: pdm install
      
      - name: install test deps
        run: |
          pdm install -dG test
          pip install pytest
        
      - name: test api
        run: |
          cd tests
          python -m test-api.py